- name: demo
  hosts: localhost
  roles:
    - Azure.azure_preview_modules
  vars:
    resource_group: yungez-ansible
    registry_name: ansibledemoacr
    repo_url: "https://github.com/Azure-Samples/aci-helloworld.git"
    workspace: ~/src/aci-helloworld
    image_name: aci-helloworld
    http_port: 80
    email: test@email.com
  tasks:
    - name: Git Clone
      git:
        repo: "{{ repo_url }}"
        dest: "{{ workspace }}"

    - name: Create Azure Container Registry
      azure_rm_containerregistry:
        resource_group: "{{ resource_group }}"
        name: "{{ registry_name}}"
        admin_user_enabled: True
        sku: Standard
      register: acr_result
    - name: Login docker registry
      docker_login:
        registry: "{{ registry_name }}.azurecr.io"
        username: "{{ registry_name }}"
        password: "{{ acr_result.credentials.password }}"
        email: "{{ email }}"
    - name: Docker Build and Push
      docker_image:
        path: "{{ workspace }}"
        name: "{{ registry_name }}.azurecr.io/{{ image_name }}"
        push: yes
    - name: Create Azure Container Instance
      azure_rm_containerinstance:
        resource_group: "{{ resource_group }}"
        name: "{{ image_name }}"
        ip_address: public
        ports:
          - "{{ http_port }}"
        registry_login_server: "{{ registry_name }}.azurecr.io"
        registry_username: "{{ registry_name }}"
        registry_password: "{{ acr_result.credentials.password }}"
        containers:
          - name: "{{ image_name }}"
            ports:
              - "{{ http_port }}"
            image: "{{ registry_name }}.azurecr.io/{{ image_name }}"
